esphome:
  name: node-bpm280
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

# Enable OTA
ota:
  password: !secret ota_password

i2c:
  sda: D1
  scl: D2
  scan: true
  id: bus_a

sensor:
  - platform: bmp280
    temperature:
      name: "temperature"
      oversampling: 16x
    pressure:
      name: "pressure"
    address: 0x76
    update_interval: 60s
